image: alpine/edge
secrets:
    - 78946f06-2da2-46f0-9a98-d40bd6362f38
environment:
    REPO: gustavlindqvist.se
    GH_USER: Reedyn
tasks:
    - push-to-github: |
          cd ~/"${REPO}"
          git config --global credential.helper store
          git push --mirror "https://github.com/${GH_USER}/${REPO}"