image: alpine/edge
secrets:
    - 78946f06-2da2-46f0-9a98-d40bd6362f38
    - 47b1a530-3bfe-482b-a5d0-a466bc38c5c8
environment:
    REPO: gustavlindqvist.se
    GH_USER: Reedyn
    COOLIFY_HOST: coolify.pokenet.cloud
    COOLIFY_CONTAINER_UUID: lk4gsg48w8c4ooo40o4ok4c0
tasks:
    - push-to-github: |
          cd ~/"${REPO}"
          git config --global credential.helper store
          git push --mirror -f "https://github.com/${GH_USER}/${REPO}"
    - deploy-coolify: |
          ls
          cd ~/"${REPO}"
          ls
          {
            set +x
            . ~/.buildsecrets
            set -x
          }
          export COOLIFY_API_TOKEN
          curl "https://${COOLIFY_HOST}/api/v1/deploy?uuid=${COOLIFY_CONTAINER_UUID}&force=true" --header "Authorization: Bearer${COOLIFY_API_TOKEN}"